### ISSUE TITLE
Static context menu?

### ISSUE THREAD

**Issue by codemakerlive** [facelessuser/EasyDiff#19]
I'd love to add this plug-in but I customise my context menu - with it being added to dynamically by this plugin it is a little too invasive for me to use. Is the dynamic element necessary - could a static context menu be used instead? Thanks,

**Comment by facelessuser** [comment]
I don't think I understand the complaint. Even if the menu was static, they would still be inserted the same by sublime.  The only difference, by being dynamic, it provides more useful info, like what file is still on the left side of the compare in case you forget.

What makes dynamic "too invasive"?  Static would get inserted as well.  As I don't think I am going to go about provided an alternate menu option type since I can see no benefit, you can try some of the options below.

You can remove the option from the view's context menu by removing view in your settings file. Then you can access it from the menu when right clicking the tab:

```js
    // Menus to show (view|tab|sidebar)
    "menu_types": ["view", "tab", "sidebar"],
```

If you want them available in the quick panel, just play with these settings:

```js
    // Show Diff menu command in the command palette
    "quick_panel_commands": false,

    // Enable manual "set left side" and "compare" commands in the panel
    "quick_panel_left_right_commands": false,

    // Show commands in the quickpanel that use the last active
    // tab as the left side.  Selection commands will look at selections
    // of both the last activated and current.
    "last_activated_commands": true,
```

**Comment by facelessuser** [comment]
Since conversation appears to have ceased on this issue, it will be closed.  If @codemakerlive chooses to begin conversation again, this issue can be re-opened.
