### ISSUE TITLE
Installation via ST2::PackageControl

### ISSUE THREAD

**Issue by Javix** [facelessuser/EasyDiff#20]
Sorry , if it is a ST2 related issue. Unfortunately, the plugin is not available for installation via ST Package Control on:
```
- SublimeText 2
- build 2221
- OS X 10.10.3.
```
Any tips on how to install it ? Thank you.

**Comment by facelessuser** [comment]
To be honest, EasyDiff does not support ST2.  Any newer plugin I've written forgo support for ST2 as I use ST3 100% now.  Older plugins support ST2 simply because I wrote them while using ST2, but no longer get updates as I simply do not have the time to support both ST2 and ST3 on all the plugins I maintain.

Sorry.
