### ISSUE TITLE
This won't install

### ISSUE THREAD

**Issue by gdwitt** [facelessuser/EasyDiff#22]
I'm following instructions here step by step.
[](http://facelessuser.github.io/EasyDiff/)
It will not show up on any windows context menus or within sublime at the locations you describe.
I am using Windows 10.
GDWitt@gmail.com

**Comment by facelessuser** [comment]
I don't know what steps you are following as you haven't really been specific, but using Package Control is the recommended way and should have no trouble.  You've posted no errors from the console.  Please install via encourage Package Control.  If Package Control is not working for you, then I suspect you have a bigger issue with your Sublime install.

**Comment by facelessuser** [comment]
I'll give it another week to see if more details will be provided, and if not, I will close this issue.

**Comment by gdwitt** [comment]
I should try it again.

**Comment by stevellwood** [comment]
Ensure Package Control is installed. Instructions are found here.
In Sublime Text, press ctrl + shift + p (Win, Linux) or cmd + shift + p (OSX) to bring up the quick panel. It will show a list of installable plugins.
Start typing EasyDiff; when you see it, select it.
Restart to be sure everything is loaded proper.
Enjoy!
This does not work. I just installed sublime and followed these instructions on my second computer. EasyDiff does not show up after trying ctrl_shift_p. Is it not included? 
Here is my package control feedback log:
"state path: /C/Users/admin/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/admin/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.852887
startup time: 0.985887
......................................................................................
reloading plugin HTML.html_completions
plugins loaded
>>> import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
186789
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
Package Control: Installing 1 missing dependency
Package Control: Installed missing dependency bz2
Package Control: No updated packages
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly."
Yes, I restarted sublime and did this twice. I am using the latest beta version of sublime 3. 3114 X64 for Windows 7.

**Comment by stevellwood** [comment]
I followed this:
cd /path/to/Sublime Text 3/Packages
git clone https://github.com/facelessuser/EasyDiff.git EasyDiff
and EasyDiff actually showed up in packages
Copy:
`:\Users\admin\AppData\Roaming>cd Sublime Text 3/Installed Packages

C:\Users\admin\AppData\Roaming\Sublime Text 3\Installed Packages>git clone https
://github.com/facelessuser/EasyDiff.git EasyDiff
Cloning into 'EasyDiff'...
remote: Counting objects: 467, done.
Receiving objects:  87% (407/467), 444emote: Total 467 (delta 0), reused 0 (delt
Receiving objects:  96% (449/467), 444.01 KiB | 873.00 KiB/s
Receiving objects: 100% (467/467), 509.85 KiB | 873.00 KiB/s, done.
Resolving deltas: 100% (259/259), done.
Checking connectivity... done.

C:\Users\admin\AppData\Roaming\Sublime Text 3\Installed Packages>`
Yes, I shut down sublime and then restarted it.
However, when I relaunch sublime, I can't find it with the cntrl shift p lookup. Is there another way to see if it is there and working?

**Comment by facelessuser** [comment]
> `C:\Users\admin\AppData\Roaming\Sublime Text 3\Installed Packages>git clone https
://github.com/facelessuser/EasyDiff.git EasyDiff`

This is why I always ask for step by step instructions to reproduce bugs.  People often say, "I followed instructions", but when pressed to give more details, there are slightly different interpretations.  The documents say to install in `Packages` **not** `Installed Packages:  http://facelessuser.github.io/EasyDiff/installation/#git-cloning.  Those little details really help a lot :smile:.

**Comment by stevellwood** [comment]
Note: the instructions say to put it into "Installed Packages":https://packagecontrol.io/installation
"Click the Preferences > Browse Packages… menu
Browse up a folder and then into the Installed Packages/ folder
Download Package Control.sublime-package and copy it into the Installed Packages/ directory
Restart Sublime Text"
.......................................
I am now getting an EasyDiff dialog on right click.
It is only active for file versions that have been init with git.
The control shift p advice does not reveal easydiff.
I wish I had a guide to using easy diff to compare just two java files in sublime even if they have not been initialized in a git repository.

**Comment by stevellwood** [comment]
Cool. I see that if I do "EasyDiff left side" then go to the other file and do "EasyDiff right side" I get a git-like comparison in one view. That's helpful
Is there a way to do interactive edits on the new comparison file itself? I can save it as a new java file, but the file is full of - and +. 
Nice tool but I was hoping for more features like I get in Winmerge or Compare++.

**Comment by facelessuser** [comment]
This is how I use EasyDiff:  I either want to see a quick diff (like you are seeing now), or I use it to send the files to something like `Beyond Compare` or `Winmerge`.  You can setup EasyDiff to either just use an external diff tool, or give you the option of the internal or external.

I didn't personally want to reinvent the wheel since I already had access to great merge tools like `Beyond Compare` etc.   If I went that route, I'd probably charge money for the plugin.   If I don't want to merge, I often just use the internal diff.  If the diff is more complex than I like, I might use the option to open in an external view.  If I want to merge, I always use EasyDiff to open in an external merge tool.  There is a paid plugin called `Sublimerge` (I think that is the name) that allows native Sublime merging...but I personally feel a dedicated merge tool like `Beyond Compare` or `Winmerge` is much better **and** more flexible option, and would rather spend my money to promote those tools that will last me even if I decide to one day not use Sublime.  Not to mention, the external diff tools work with the OS file manager, so I don't have to open a file in Sublime to merge or see the diff if I don't want to.

Everybody has different preferences I suppose. I usually approach my plugins (since I do them for free) to accommodate my workflow.   I don't mind adding features that I may not use, but something like a full featured internal diff/merge tool would require too much of my time to create and maintain which I just can't justify when I already have great merge and diff options.  Instead, I opt to provide access to those great tools, and optionally provide a quick internal diff.
