### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by xtotdam** [facelessuser/EasyDiff#25]
Please add some screenshots
For me using EasyDiff means upgrading from ST2 to ST3 and seemingly breaking some other plugins, so it is kinda hard to make a decision :)

**Comment by facelessuser** [comment]
There isn't really screenshots because there isn't much to show.  If you do an in view diff, you just get a basic diff like this:

```diff
diff --git a/support.py b/support.py
index 7dd5a95..eedbeeb 100644
--- a/support.py
+++ b/support.py
@@ -5,7 +5,7 @@ import textwrap
 import webbrowser
 import re
 
-__version__ = "2.0.2"
+__version__ = "2.0.3"
 __pc_name__ = 'EasyDiff'
 
 CSS = '''

```

If you are setup to use an external diff tool, then it opens in your diff tool.

Other than that, you get context menus as shown in the one provided screenshot.

Personally, I'd upgrade to ST3 regardless of whether you use EasyDiff. ST3 is much better in general and is actively supported.  I can't speak for whatever legacy plugins your using, but I image if they aren't on ST3, they probably aren't actively supported either, but I can understand the attachment to plugins you are used to.

Anyways, hopefully I clarified what EasyDiff is.  If you are still confused, just try out ST3 for free and install EasyDiff and and you can get an idea of what it does.  You should be able to have ST2 and ST3 installed side by side.

**Comment by facelessuser** [comment]
As a case for adding screenshots hasn't really been made, I'm going to close this issue.
